# Generated by Django 4.2.1 on 2023-06-04 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_demandeacces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeacces',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
