# Generated by Django 4.2.1 on 2023-06-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=60)),
                ('course_level', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('course_pdf', models.FileField(upload_to='pdfs/')),
                ('video_url', models.URLField()),
                ('cover_image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
