# Generated by Django 4.2.1 on 2023-06-30 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_course_duration_hours_course_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
