# Generated by Django 4.2.1 on 2023-07-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_quiz_quiz_duration_quiz_quiz_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
