# Generated by Django 4.2.2 on 2023-07-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_course_is_subscribed_etudiant_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
