# Generated by Django 4.2.2 on 2023-07-09 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_course_is_opened'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_opened',
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_opened', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='courses',
            field=models.ManyToManyField(through='account.Enrollment', to='account.course'),
        ),
    ]
